### ISSUE TITLE
The QR Code needs a "quiet zone"

### ISSUE THREAD

**Issue by denilsonsa** [DoctorLai/simple-qr-code#1]
The generated QR codes from this extension cannot be scanned because they lack the "quiet zone". Around the QR code there must be an empty/blank/white area of at least 4 modules (i.e. 4 little squares). Look: https://www.google.com/search?q=qr+code+quiet+zone&tbm=isch

There are two possible solutions:

1. The generated image could contain the quiet zone embedded into the image pixels.
2. When displaying the QR code, just add a CSS `padding` around the image.

**Comment by denilsonsa** [comment]
Also, as a minor side note, I just noticed you are not using Bootstrap anymore, so you could remove it from [`main.html`](https://github.com/DoctorLai/simple-qr-code/blob/master/simple-qr-code/main.html) and from the extension itself.

**Comment by DoctorLai** [comment]
Thank you, I’ll fix this soon.

**Comment by DoctorLai** [comment]
@denilsonsa   Fixed in version 1.3.2. Wait for the updates pushed by Google webstore or you can go to https://github.com/DoctorLai/simple-qr-code/releases to install locally. Thanks
